manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: sdk-nrf
      remote: nrfconnect
      revision: 8c006d50e62d5b0b706dd177fa27935a4d7dfc05
      path: nrf
      import: true
  self:
    path: fw
