manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: sdk-nrf
      remote: nrfconnect
      revision: 68e74a0d749ecf39aac711c1e7df34585dddec32
      path: nrf
      import: true
  self:
    path: fw
